[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Optimizer settings
optimizer = true
optimizer_runs = 1000000
via_ir = false

# Gas reporting
gas_reports = ["Shop"]
gas_reports_ignore = []

# Coverage settings
coverage_exclude = ["test/**", "script/**", "lib/**"]

# Test settings
verbosity = 2
fuzz = { runs = 256 }
invariant = { runs = 256 }

# Compiler settings
solc_version = "0.8.30"
evm_version = "paris"

# Formatter settings
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
